version: "3"
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_test
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: prj
    